version: '3'
services:
  node:
    tty: true
    container_name: node
    image: node:13.10
    ports: 
      - 8080:8080
    volumes:
      - ./:/app
    # command: bash -c "chmod 777 -R /app && cd /app/sample && npm run serve"